version: "3"
services:
    db:
        container_name: movies_db
        image: postgres:14-alpine
        ports:
            - "32001:5432"
        environment:
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"