version: "3"
services:
    db:
        container_name: orders
        image: mysql:8.0
        platform: linux/amd64
        ports:
            - "32002:3306"
        environment:
            - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        volumes:
            - "./orders.sql:/docker-entrypoint-initdb.d/orders.sql"
