version: "3"
services:
    db:
        container_name: postgres_db
        image: postgres:14-alpine
        ports:
            - "32001:5432"
        environment:
            - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
        volumes:
            - "../../SampleDatabases/pagila_postgres:/docker-entrypoint-initdb.d"
